[package]
name = "fast-text-splitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fast_text_splitter"
#crate-type = ["cdylib"]

[dependencies]
tokenizers = { version = "0.19.1", features = ["http"], optional = true }
aho-corasick = "=1.1.3"
anyhow = "1.0.83"
rayon = "1.10.0"
pyo3 = "0.21.2"
lazy_static = "1.4.0"
once_cell = "1.9"
dashmap = "5.0"
memchr = "2.7.2"
unicode-normalization = "0.1.23"
num_cpus = "1.16.0"
unicode_categories = "0.1.1"
serde = { version = "1.0.197", features = ["derive"] }
itertools = "0.13.0"

[features]
default = []
tokenizers = ["dep:tokenizers"]


[dev-dependencies]
criterion = "0.5.1"
memchr = "2.7.2"
tokenizers = "0.19.1"
tempfile = "3.2.0"

[[bench]]
name = "benchmarks"
harness = false