use std::fmt;
use std::str::FromStr;

#[derive(Debug, PartialEq)]
pub enum Language {
    CPP,
    GO,
    JAVA,
    KOTLIN,
    JS,
    TS,
    PHP,
    PROTO,
    PYTHON,
    RST,
    RUBY,
    RUST,
    SCALA,
    SWIFT,
    MARKDOWN,
    LATEX,
    HTML,
    SOL,
    CSHARP,
    COBOL,
    C,
    LUA,
    PERL,
    HASKELL,
    ELIXIR,
    POWERSHELL,
}

impl Language {
    pub fn get_separators(&self) -> Vec<Vec<String>> {
        match self {
            Language::CPP | Language::C => vec![vec![
                "\nclass ".to_string(),
                "\nvoid ".to_string(),
                "\nint ".to_string(),
                "\nfloat ".to_string(),
                "\ndouble ".to_string(),
                "\nif ".to_string(),
                "\nfor ".to_string(),
                "\nwhile ".to_string(),
                "\nswitch ".to_string(),
                "\ncase ".to_string(),
                "\n\n".to_string(),
                "\n".to_string(),
                " ".to_string(),
            ]],
            Language::GO => vec![vec![
                "\nfunc ".to_string(),
                "\nvar ".to_string(),
                "\nconst ".to_string(),
                "\ntype ".to_string(),
                "\nif ".to_string(),
                "\nfor ".to_string(),
                "\nswitch ".to_string(),
                "\ncase ".to_string(),
                "\n\n".to_string(),
                "\n".to_string(),
                " ".to_string(),
                "".to_string(),
            ]],
            Language::JAVA => vec![vec![
                "\nclass ".to_string(),
                "\npublic ".to_string(),
                "\nprotected ".to_string(),
                "\nprivate ".to_string(),
                "\nstatic ".to_string(),
                "\nif ".to_string(),
                "\nfor ".to_string(),
                "\nwhile ".to_string(),
                "\nswitch ".to_string(),
                "\ncase ".to_string(),
                "\n\n".to_string(),
                "\n".to_string(),
                " ".to_string(),
                "".to_string(),
            ]],
            Language::KOTLIN => vec![vec![
                "\nclass ".to_string(),
                "\npublic ".to_string(),
                "\nprotected ".to_string(),
                "\nprivate ".to_string(),
                "\ninternal ".to_string(),
                "\ncompanion ".to_string(),
                "\nfun ".to_string(),
                "\nval ".to_string(),
                "\nvar ".to_string(),
                "\nif ".to_string(),
                "\nfor ".to_string(),
                "\nwhile ".to_string(),
                "\nwhen ".to_string(),
                "\ncase ".to_string(),
                "\nelse ".to_string(),
                "\n\n".to_string(),
                "\n".to_string(),
                " ".to_string(),
                "".to_string(),
            ]],
            Language::JS => vec![vec![
                "\nfunction ".to_string(),
                "\nconst ".to_string(),
                "\nlet ".to_string(),
                "\nvar ".to_string(),
                "\nclass ".to_string(),
                "\nif ".to_string(),
                "\nfor ".to_string(),
                "\nwhile ".to_string(),
                "\nswitch ".to_string(),
                "\ncase ".to_string(),
                "\ndefault ".to_string(),
                "\n\n".to_string(),
                "\n".to_string(),
                " ".to_string(),
                "".to_string(),
            ]],
            Language::TS => vec![vec![
                "\nenum ".to_string(),
                "\ninterface ".to_string(),
                "\nnamespace ".to_string(),
                "\ntype ".to_string(),
                "\nclass ".to_string(),
                "\nfunction ".to_string(),
                "\nconst ".to_string(),
                "\nlet ".to_string(),
                "\nvar ".to_string(),
                "\nif ".to_string(),
                "\nfor ".to_string(),
                "\nwhile ".to_string(),
                "\nswitch ".to_string(),
                "\ncase ".to_string(),
                "\ndefault ".to_string(),
                "\n\n".to_string(),
                "\n".to_string(),
                " ".to_string(),
                "".to_string(),
            ]],
            Language::PHP => vec![vec![
                "\nfunction ".to_string(),
                "\nclass ".to_string(),
                "\nif ".to_string(),
                "\nforeach ".to_string(),
                "\nwhile ".to_string(),
                "\ndo ".to_string(),
                "\nswitch ".to_string(),
                "\ncase ".to_string(),
                "\n\n".to_string(),
                "\n".to_string(),
                " ".to_string(),
                "".to_string(),
            ]],
            Language::PROTO => vec![vec![
                "\nmessage ".to_string(),
                "\nservice ".to_string(),
                "\nenum ".to_string(),
                "\noption ".to_string(),
                "\nimport ".to_string(),
                "\nsyntax ".to_string(),
                "\n\n".to_string(),
                "\n".to_string(),
                " ".to_string(),
                "".to_string(),
            ]],
            Language::PYTHON => vec![
                vec!["\nclass ".to_string(), "\ndef ".to_string()],
                vec!["\n\tdef ".to_string(), "\n\n".to_string()],
                vec!["\n".to_string()],
                vec![" ".to_string()],
            ],
            _ => vec![vec!["\n".to_string(), " ".to_string()]],
        }
    }
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl FromStr for Language {
    type Err = ();

    fn from_str(input: &str) -> Result<Language, Self::Err> {
        match input {
            "cpp" => Ok(Language::CPP),
            "go" => Ok(Language::GO),
            "java" => Ok(Language::JAVA),
            "kotlin" => Ok(Language::KOTLIN),
            "js" => Ok(Language::JS),
            "ts" => Ok(Language::TS),
            "php" => Ok(Language::PHP),
            "proto" => Ok(Language::PROTO),
            "python" => Ok(Language::PYTHON),
            "rst" => Ok(Language::RST),
            "ruby" => Ok(Language::RUBY),
            "rust" => Ok(Language::RUST),
            "scala" => Ok(Language::SCALA),
            "swift" => Ok(Language::SWIFT),
            "markdown" => Ok(Language::MARKDOWN),
            "latex" => Ok(Language::LATEX),
            "html" => Ok(Language::HTML),
            "sol" => Ok(Language::SOL),
            "csharp" => Ok(Language::CSHARP),
            "cobol" => Ok(Language::COBOL),
            "c" => Ok(Language::C),
            "lua" => Ok(Language::LUA),
            "perl" => Ok(Language::PERL),
            "haskell" => Ok(Language::HASKELL),
            "elixir" => Ok(Language::ELIXIR),
            "powershell" => Ok(Language::POWERSHELL),
            _ => Err(()),
        }
    }
}
